name: Test lodns-action

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Test lodns-action on ${{ matrix.os }}
    steps:
      - name: lodns
        uses: vandot/lodns-action@${{ github.ref_name }}
      - name: Test server
        if: matrix.os != 'windows-latest'
        run: |
          dig A example.lo
          ping -c 1 example.lo
      - name: Test server
        if: matrix.os == 'windows-latest'
        run: |
          nslookup example.lo
          ping /n 1 example.lo
  test-2204:
    runs-on: ubuntu-latest
    name: Test lodns-action install-only
    steps:
      - name: lodns
        uses: vandot/lodns-action@${{ github.ref_name }}
        with:
          install-only: true
      - name: Test lodns
        run: |
          lodns
