name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test lodns action
    steps:
      - name: lodns
        uses: vandot/lodns-action@test
      - name: debug
        run: |
          echo "##### INTERFACES #####"
          ifconfig
          echo "##### LIST PROCESS #####"
          ps aux | grep lodns
          echo "##### LIST  PORTS #####"
          netstat -lpun
          echo "##### NETWORK FILE #####"
          cat /etc/systemd/network/lodns0.network
          echo "##### DEVICE FILE #####"
          cat /etc/systemd/network/lodns0.netdev
        # with:
        #   install-only: true
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Test server
        run: |
          dig A example.lo
          ping -c 1 example.lo
  test-2204:
    runs-on: ubuntu-22.04
    name: Test lodns action 22.04
    steps:
      - name: lodns
        uses: vandot/lodns-action@test
      - name: debug
        run: |
          echo "##### INTERFACES #####"
          ifconfig
          echo "##### LIST PROCESS #####"
          ps aux | grep lodns
          echo "##### LIST  PORTS #####"
          netstat -lpun
          echo "##### NETWORK FILE #####"
          cat /etc/systemd/network/lodns0.network
          echo "##### DEVICE FILE #####"
          cat /etc/systemd/network/lodns0.netdev
        # with:
        #   install-only: true
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Test server
        run: |
          dig A example.lo
          ping -c 1 example.lo
