name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test lodns action
    steps:
      - name: lodns
        uses: vandot/lodns-action@main
      - name: Test server
        run: |
          dig @127.0.0.1 A example.lo
