name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test lodns action
    steps:
      - name: lodns
        uses: vandot/lodns-action@test
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Test server
        run: |
          dig @169.254.1.1 A example.lo
          ping -c 1 example.lo
